language: cpp
script:
  - cmake --version
  - sh .travis_build.sh linux 
matrix:
  include:
    # Linux Clang
    - os: linux
      compiler: clang
      env: BUILD_TYPE='Release'
    - os: linux
      compiler: clang
      env: BUILD_TYPE='Debug'
    # Linux GCC
    - os: linux
      compiler: gcc
      addons: &gcc48
        apt:
         sources: ['ubuntu-toolchain-r-test']
         packages: ['g++-4.8']
      env: BUILD_TYPE='Release'
    - os: linux
      compiler: gcc
      addons: &gcc48
        apt:
         sources: ['ubuntu-toolchain-r-test']
         packages: ['g++-4.8']
      env: BUILD_TYPE='Debug'
    # OS X
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILD_TYPE='Release'
